/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zq.GraphGen;

import org.gephi.lib.validation.PositiveNumberValidator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationPanel;

/**
 *
 * @author zqlee1
 */
public class PreferentialAttachmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form PreferentialAttachmentPanel
     */
    public PreferentialAttachmentPanel() {
        initComponents();
    }

    public static ValidationPanel createValidationPanel(PreferentialAttachmentPanel innerPanel) {
        ValidationPanel validationPanel = new ValidationPanel();
        if (innerPanel == null) {
            innerPanel = new PreferentialAttachmentPanel();
        }
        validationPanel.setInnerComponent(innerPanel);

        ValidationGroup group = validationPanel.getValidationGroup();

        //Node field
        group.add(innerPanel.nodeField, Validators.REQUIRE_NON_EMPTY_STRING,
                new PositiveNumberValidator());

        //Edge field
        group.add(innerPanel.edgeField, Validators.REQUIRE_NON_EMPTY_STRING,
                new PositiveNumberValidator());

        //Num initial node field
        group.add(innerPanel.initNodeField, Validators.REQUIRE_NON_EMPTY_STRING,
                new PositiveNumberValidator());

        return validationPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nodeField = new javax.swing.JTextField();
        edgeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        initNodeField = new javax.swing.JTextField();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PreferentialAttachmentPanel.class, "PreferentialAttachmentPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PreferentialAttachmentPanel.class, "PreferentialAttachmentPanel.jLabel2.text")); // NOI18N

        nodeField.setText(org.openide.util.NbBundle.getMessage(PreferentialAttachmentPanel.class, "PreferentialAttachmentPanel.nodeField.text")); // NOI18N
        nodeField.setName(org.openide.util.NbBundle.getMessage(PreferentialAttachmentPanel.class, "PreferentialAttachmentPanel.nodeField.name")); // NOI18N
        nodeField.setPreferredSize(new java.awt.Dimension(100, 20));

        edgeField.setText(org.openide.util.NbBundle.getMessage(PreferentialAttachmentPanel.class, "PreferentialAttachmentPanel.edgeField.text")); // NOI18N
        edgeField.setName(org.openide.util.NbBundle.getMessage(PreferentialAttachmentPanel.class, "PreferentialAttachmentPanel.edgeField.name")); // NOI18N
        edgeField.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(PreferentialAttachmentPanel.class, "PreferentialAttachmentPanel.jLabel3.text")); // NOI18N

        initNodeField.setText(org.openide.util.NbBundle.getMessage(PreferentialAttachmentPanel.class, "PreferentialAttachmentPanel.initNodeField.text")); // NOI18N
        initNodeField.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(initNodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(initNodeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        nodeField.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(PreferentialAttachmentPanel.class, "PreferentialAttachmentPanel.jTextField1.AccessibleContext.accessibleName")); // NOI18N
        edgeField.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(PreferentialAttachmentPanel.class, "PreferentialAttachmentPanel.jTextField2.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField edgeField;
    protected javax.swing.JTextField initNodeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    protected javax.swing.JTextField nodeField;
    // End of variables declaration//GEN-END:variables
}
